#!/bin/sh

CC=gcc
CFLAGS="-g -Wall -o"
LDFLAGS=

LIBS=

MAINFOLDER="src/core"
TESTFOLDER="src/test"

MAINSOURCE="$MAINFOLDER/psafe.c"
SUPPSOURCES="$MAINFOLDER/psafeKey.c $MAINFOLDER/literalOperations.c $MAINFOLDER/arrayOperations.c"

MAINBIN="psafe"
TESTBIN="test"

BIN=
SOURCES=

function compile {
  ($CC $CFLAGS $BIN $SOURCES $LIBS)
  return $?
}

function setMainSources {
  BIN=$MAINBIN
  SOURCES="$MAINSOURCE $SUPPSOURCES"
  return $?   
}

function setTestSources {
  BIN=$TESTBIN
  SOURCES="$TESTFOLDER/psafeTestSuite.c $TESTFOLDER/psafeKeyTests.c $TESTFOLDER/arrayOperationsTests.c $TESTFOLDER/literalOperationsTests.c $SUPPSOURCES"
  LIBS="`pkg-config --libs cunit`"
  return 0
}

case "$1" in
  test )
    setTestSources
    compile
    exit $?
    ;;
  clean )
    rm -f $MAINBIN $TESTBIN
    exit 0
    ;;
  * )
    setMainSources
    compile
    exit $?
    ;;
esac

