#!/bin/sh

CC=gcc
CFLAGS="-g -Wall -o"
LDFLAGS=

LIBS=

MAINFOLDER="src/core"
TESTFOLDER="src/test"

BIN=
SOURCES=

function compile {
  ($CC $CFLAGS $BIN $SOURCES $LIBS)
  return $?
}

function setMainSources {
  BIN="psafe"
  SOURCES="$MAINFOLDER/psafe.c $MAINFOLDER/psafeKey.c $MAINFOLDER/literalOperations.c"
  return $?   
}

function setTestSources {
  BIN="test"
  SOURCES="$TESTFOLDER/psafeTestSuite.c $TESTFOLDER/psafeKeyTests.c $TESTFOLDER/literalOperationsTests.c $MAINFOLDER/psafeKey.c $MAINFOLDER/literalOperations.c"
  LIBS="`pkg-config --libs cunit`"
  return 0
}

case "$1" in
  test )
    setTestSources
    compile
    exit $?
    ;;
  clean )
    rm -f $MAINBIN $TESTBIN
    exit 0
    ;;
  * )
    setMainSources
    compile
    exit $?
    ;;
esac

