# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /git/cph

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /git/cph

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /git/cph/CMakeFiles /git/cph/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /git/cph/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cph

# Build rule for target.
cph: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cph
.PHONY : cph

# fast build rule for target.
cph/fast:
	$(MAKE) -f CMakeFiles/cph.dir/build.make CMakeFiles/cph.dir/build
.PHONY : cph/fast

src/cph.o: src/cph.c.o
.PHONY : src/cph.o

# target to build an object file
src/cph.c.o:
	$(MAKE) -f CMakeFiles/cph.dir/build.make CMakeFiles/cph.dir/src/cph.c.o
.PHONY : src/cph.c.o

src/cph.i: src/cph.c.i
.PHONY : src/cph.i

# target to preprocess a source file
src/cph.c.i:
	$(MAKE) -f CMakeFiles/cph.dir/build.make CMakeFiles/cph.dir/src/cph.c.i
.PHONY : src/cph.c.i

src/cph.s: src/cph.c.s
.PHONY : src/cph.s

# target to generate assembly for a file
src/cph.c.s:
	$(MAKE) -f CMakeFiles/cph.dir/build.make CMakeFiles/cph.dir/src/cph.c.s
.PHONY : src/cph.c.s

src/cph_clipboard_handler.o: src/cph_clipboard_handler.c.o
.PHONY : src/cph_clipboard_handler.o

# target to build an object file
src/cph_clipboard_handler.c.o:
	$(MAKE) -f CMakeFiles/cph.dir/build.make CMakeFiles/cph.dir/src/cph_clipboard_handler.c.o
.PHONY : src/cph_clipboard_handler.c.o

src/cph_clipboard_handler.i: src/cph_clipboard_handler.c.i
.PHONY : src/cph_clipboard_handler.i

# target to preprocess a source file
src/cph_clipboard_handler.c.i:
	$(MAKE) -f CMakeFiles/cph.dir/build.make CMakeFiles/cph.dir/src/cph_clipboard_handler.c.i
.PHONY : src/cph_clipboard_handler.c.i

src/cph_clipboard_handler.s: src/cph_clipboard_handler.c.s
.PHONY : src/cph_clipboard_handler.s

# target to generate assembly for a file
src/cph_clipboard_handler.c.s:
	$(MAKE) -f CMakeFiles/cph.dir/build.make CMakeFiles/cph.dir/src/cph_clipboard_handler.c.s
.PHONY : src/cph_clipboard_handler.c.s

src/cph_input_handler.o: src/cph_input_handler.c.o
.PHONY : src/cph_input_handler.o

# target to build an object file
src/cph_input_handler.c.o:
	$(MAKE) -f CMakeFiles/cph.dir/build.make CMakeFiles/cph.dir/src/cph_input_handler.c.o
.PHONY : src/cph_input_handler.c.o

src/cph_input_handler.i: src/cph_input_handler.c.i
.PHONY : src/cph_input_handler.i

# target to preprocess a source file
src/cph_input_handler.c.i:
	$(MAKE) -f CMakeFiles/cph.dir/build.make CMakeFiles/cph.dir/src/cph_input_handler.c.i
.PHONY : src/cph_input_handler.c.i

src/cph_input_handler.s: src/cph_input_handler.c.s
.PHONY : src/cph_input_handler.s

# target to generate assembly for a file
src/cph_input_handler.c.s:
	$(MAKE) -f CMakeFiles/cph.dir/build.make CMakeFiles/cph.dir/src/cph_input_handler.c.s
.PHONY : src/cph_input_handler.c.s

src/cph_key.o: src/cph_key.c.o
.PHONY : src/cph_key.o

# target to build an object file
src/cph_key.c.o:
	$(MAKE) -f CMakeFiles/cph.dir/build.make CMakeFiles/cph.dir/src/cph_key.c.o
.PHONY : src/cph_key.c.o

src/cph_key.i: src/cph_key.c.i
.PHONY : src/cph_key.i

# target to preprocess a source file
src/cph_key.c.i:
	$(MAKE) -f CMakeFiles/cph.dir/build.make CMakeFiles/cph.dir/src/cph_key.c.i
.PHONY : src/cph_key.c.i

src/cph_key.s: src/cph_key.c.s
.PHONY : src/cph_key.s

# target to generate assembly for a file
src/cph_key.c.s:
	$(MAKE) -f CMakeFiles/cph.dir/build.make CMakeFiles/cph.dir/src/cph_key.c.s
.PHONY : src/cph_key.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... cph"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/cph.o"
	@echo "... src/cph.i"
	@echo "... src/cph.s"
	@echo "... src/cph_clipboard_handler.o"
	@echo "... src/cph_clipboard_handler.i"
	@echo "... src/cph_clipboard_handler.s"
	@echo "... src/cph_input_handler.o"
	@echo "... src/cph_input_handler.i"
	@echo "... src/cph_input_handler.s"
	@echo "... src/cph_key.o"
	@echo "... src/cph_key.i"
	@echo "... src/cph_key.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

