#!/bin/bash

help() {
    cat <<EOF
usage: package VERSION TARGET
    TARGET can be one of: package_src
EOF
}

package_src () {
  local TMP_DIR="cph-$1"

  rm -rf "$TMP_DIR" && mkdir "$TMP_DIR"

  cp -r src "$TMP_DIR"/

  cp readme.md LICENSE "$TMP_DIR"/
  cp CMakeLists.txt FindLibgcrypt.cmake configure "$TMP_DIR"/

  tar -czf "$TMP_DIR".tar.gz "$TMP_DIR"

  rm -rf "$TMP_DIR"
}

VERSION=$1
TARGET=$2

[ -z "$VERSION" -o -z "$TARGET" ] && help && exit 1

case $TARGET in
  src)
    package_src "$VERSION"
    ;;
  *)
    echo "unknown target: $*" && help && exit 1
esac
