#!/usr/bin/env python
"""Wrapper for psafe to pass passwords to the clipboard."""

from subprocess import Popen, PIPE
import sys
import os
import time
import getpass

HELP_MSG = "pysafe [options] <profile> [key size]"

def text_to_clipboard(text):
    """Parse text to clipboard."""
    Popen(['xsel', '-pi'], stdin=PIPE).communicate(text)

def clear_clipboard():
    """Delete clipboard contents."""
    Popen(['xsel', '-d'])

def main(argv):
    """pysafe main method"""
    argc = len(argv)
    if argc < 1 or argc > 2:
        print(HELP_MSG)
        sys.exit(1)

    for opt in argv:
        if opt in ("-h", "--help"):
            print(HELP_MSG)
            sys.exit()

    profile = argv[0]
    pwd = getpass.getpass()
    if argc == 2:
        key_size = argv[1]
        psafe_call = ['./psafe', profile, pwd, key_size]
    else:
        psafe_call = ['./psafe', profile, pwd]
      
    # run psafe and save output
    process = Popen(psafe_call, shell=False, stdout=PIPE,
        stderr=PIPE)

    out, err = process.communicate()

    # if stderr not empty, exit and print errors
    if not err:
        text_to_clipboard(out)
    else:
        print(err.decode("utf-8"))
        sys.exit(1)

    # now fork and sleep!
    if os.fork():
        sys.exit()

    time.sleep(10)

    clear_clipboard()

    sys.exit(0)


if  __name__ =='__main__':
    main(sys.argv[1:])
