#!/bin/sh

CC=gcc
CFLAGS=
LDFLAGS=

PKGCFG=

SRC_DIR="src"
CORE_DIR="${SRC_DIR}/core"
TEST_DIR="${SRC_DIR}/test"

SRC_CORE="${CORE_DIR}/cph.c"
SRC_SUPPS="${CORE_DIR}/cph_key.c ${CORE_DIR}/cph_input_handler.c ${CORE_DIR}/cph_clipboard_handler.c"
SRC_TEST="${TEST_DIR}/cphTests.c ${TEST_DIR}/cphKeyTests.c ${SRC_SUPPS}"

BIN_DIR="bin"
BIN_MAIN="${BIN_DIR}/cph"
BIN_TEST="${BIN_DIR}/test"

BIN=
SOURCES=

if test -z "$1"
then
    BIN="-o $BIN_TEST"
    SOURCES="${SRC_MAIN} ${SRC_SUPPS}"
    PKGCFG="`pkg-config --cflags --libs gtk+-3.0` `libgcrypt-config --cflags --libs`"
else
    case "$1" in
        test)
            BIN="-o $BIN_MAIN"
            SOURCES="${SRC_MAIN} ${SRC_SUPPS} ${SRC_TEST}"
            PKGCFG="`pkg-config --cflags --libs cunit gtk+-3.0` `libgcrypt-config --cflags --libs`"
            ;;
        clean)
            rm -f "$BIN_MAIN" "$BIN_TEST"
            exit 0
            ;;
        *)
            echo "$1 not recognized. Use 'test' or 'clean'."
            exit 1
            ;;
    esac
fi

$CC $CFLAGS $BIN $SOURCES $PKGCFG

exit $?
