#!/bin/sh

COUNT=${1:-1000}

LENGTH=${2:-16}

for i in `seq 1 $COUNT`;
do
    word=$(pwgen -N1 77)
    salt=$(pwgen -N1 22)
    if [ ! -e "../bin/cph" ]
    then
        pushd .. &>/dev/null
        make clean
        make
        popd &>/dev/null
    fi

    ../bin/cph -w "$word" -s "$salt" -l "$LENGTH" -e

    # if [ ! ${#OUTPUT} -eq $LENGTH ]
    # then
    #     echo "cph -w $word -s $salt -l $LENGTH"
    #     echo "$OUTPUT"
    # else
    #     echo "${#OUTPUT}"
    # fi
done
